create table colors (
    -- id integer generated by default as identity primary key,
    id integer generated always as identity primary key,
    name varchar(50) not null
);

drop table colors;

insert into colors(name) values ('Red');
-- insert into colors values (2, 'Green');
-- insert into colors values (3, 'Blue');

select * from colors;